Repository KSP-CKAN/CKAN-meta, pull requests merged in 2020-05, with the labels that each got.

#1909 Backfill KSPIE
  KSPInterstellarExtended/KSPInterstellarExtended-1.25.15.1.ckan
Labels: Easy

#1919 Make historical ASETAvionics compatible with all game versions
  ASETAvionics/ASETAvionics-1.0.ckan
  ASETAvionics/ASETAvionics-2.0.ckan
Labels: Easy, Fix compatibility

#1920 Make historical ASETProps compatible with all game versions
  ASETProps/ASETProps-1.3.ckan
  ASETProps/ASETProps-1.4.ckan
Labels: Easy, Fix compatibility

#1923 Fix historical compatibility for SeparatorDestroyer
  SeparatorDestroyer/SeparatorDestroyer-1.0.0.0.ckan
  SeparatorDestroyer/SeparatorDestroyer-1.0.0.1.ckan
Labels: Fix compatibility, Fix relationships

#2003 Fix historical RSSDateTimeFormatter compatibility
  RSSDateTimeFormatter/RSSDateTimeFormatter-1.4.3.0.ckan
  RSSDateTimeFormatter/RSSDateTimeFormatter-1.4.5.0.ckan
  RSSDateTimeFormatter/RSSDateTimeFormatter-1.5.1.0.ckan
Labels: Fix compatibility
