Repository KSP-CKAN/CKAN-meta, pull requests merged in 2020-01, with the labels that each got.

#1738 Assorted fixes for Mk1RPMInternal
  Mk1RPMInternal/Mk1RPMInternal-1-2.2.ckan
  Mk1RPMInternal/Mk1RPMInternal-2.11.ckan
  Mk1RPMInternal/Mk1RPMInternal-2.11b.ckan
  Mk1RPMInternal/Mk1RPMInternal-2.11c.ckan
Labels: Easy, Fix relationships

#1741 Set old SXTContinued licenses
  SXTContinued/SXTContinued-0.3.0-beta.ckan
  SXTContinued/SXTContinued-0.3.10.ckan
  SXTContinued/SXTContinued-0.3.11.1.ckan
  SXTContinued/SXTContinued-0.3.11.ckan
  SXTContinued/SXTContinued-0.3.12.1.ckan
  SXTContinued/SXTContinued-0.3.12.ckan
  SXTContinued/SXTContinued-0.3.14.ckan
  SXTContinued/SXTContinued-0.3.2-beta.ckan
  SXTContinued/SXTContinued-0.3.2.1-beta.ckan
  SXTContinued/SXTContinued-0.3.3.ckan
  SXTContinued/SXTContinued-0.3.4.ckan
  SXTContinued/SXTContinued-0.3.5.ckan
  SXTContinued/SXTContinued-0.3.6.ckan
  SXTContinued/SXTContinued-0.3.7.1.ckan
  SXTContinued/SXTContinued-0.3.8.ckan
  SXTContinued/SXTContinued-0.3.9.1.ckan
  SXTContinued/SXTContinued-0.3.9.ckan
  SXTContinued/SXTContinued-0313.ckan
  SXTContinued/SXTContinued-1-0.3.14.ckan
  SXTContinued/SXTContinued-1-0.3.16.ckan
  SXTContinued/SXTContinued-1-0.3.17.ckan
  SXTContinued/SXTContinued-1-0.3.18.ckan
  SXTContinued/SXTContinued-1-0.3.19.ckan
  SXTContinued/SXTContinued-1-0.3.20.ckan
  SXTContinued/SXTContinued-1-0.3.21.ckan
  SXTContinued/SXTContinued-1-0.3.22.ckan
  SXTContinued/SXTContinued-1-0.3.23.1.ckan
  SXTContinued/SXTContinued-1-0.3.23.2.ckan
  SXTContinued/SXTContinued-1-0.3.23.3.ckan
  SXTContinued/SXTContinued-1-0.3.23.4.ckan
  SXTContinued/SXTContinued-1-0.3.23.5.ckan
  SXTContinued/SXTContinued-1-0.3.23.6.ckan
  SXTContinued/SXTContinued-1-0.3.23.7.ckan
  SXTContinued/SXTContinued-1-0.3.24.1.ckan
  SXTContinued/SXTContinued-1-0.3.24.2.ckan
  SXTContinued/SXTContinued-1-0.3.24.3.ckan
  SXTContinued/SXTContinued-1-0.3.24.ckan
  SXTContinued/SXTContinued-1-0.3.25.1.ckan
  SXTContinued/SXTContinued-1-0.3.25.2.ckan
  SXTContinued/SXTContinued-1-0.3.25.ckan
  SXTContinued/SXTContinued-1-0.3.26.ckan
  SXTContinued/SXTContinued-1-0.3.27.ckan
  SXTContinued/SXTContinued-1-0.3.28.1.ckan
  SXTContinued/SXTContinued-1-0.3.28.2.ckan
  SXTContinued/SXTContinued-1-0.3.28.ckan
  SXTContinued/SXTContinued-1-03.28.2.ckan
  SXTContinued/SXTContinued-2-0.3.29.ckan
Labels: Easy, Fix license

#1745 Set fourth group of historical unknown licenses
  AoATechnologies/AoATechnologies-1.3.7.2.ckan
  AoATechnologies/AoATechnologies-1.3.7.frozen
  AoATechnologies/AoATechnologies-1.3.8.1_pre.ckan
  AoATechnologies/AoATechnologies-1.3.8_pre.ckan
  AoATechnologies/AoATechnologies-1.3.9.1.ckan
  AoATechnologies/AoATechnologies-1.3.9.ckan
  AoATechnologies/AoATechnologies-1.4.ckan
  KittopiaTech/KittopiaTech-0.192.frozen
  Mk-X/Mk-X-0.0.2.ckan
  MoarFEConfigs/MoarFEConfigs-1.0.ckan
  StructuralDisks/StructuralDisks-1.0.2.ckan
  StructuralDisks/StructuralDisks-1.1.0.ckan
  StructuralDisks/StructuralDisks-1.2.0.1.ckan
  VentralDrill/VentralDrill-1.2.2.1.ckan
  VentralDrill/VentralDrill-1.2.2.ckan
  VentralDrill/VentralDrill-1.3.0.ckan
  VentralDrill/VentralDrill-1.4.3.ckan
Labels: Easy, Fix license

#1757 CommNetAntennasExtension max version
  CommNetAntennasExtension/CommNetAntennasExtension-2.0.1.ckan
  CommNetAntennasExtension/CommNetAntennasExtension-2.1.0.ckan
Labels: Discussion needed

#1758 Fix historical EarnYourStripes homepages
  EarnYourStripes/EarnYourStripes-2.0.ckan
  EarnYourStripes/EarnYourStripes-2.1.ckan
  EarnYourStripes/EarnYourStripes-2.2.ckan
Labels: Easy
