Repository KSP-CKAN/CKAN-meta, pull requests merged in 2021-11, with the labels that each got.

#2499 Conflicts between MinorPlanetsExpansionRevived and MinorPlanetsExpansion
  MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.1.1.ckan
  MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.1.2.ckan
  MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.1.3.ckan
  MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.1.4.ckan
  MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.1.5.ckan
  MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.1.6.ckan
  MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.2.0.ckan
  MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.2.1.ckan
  MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.2.2.ckan
  MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.3.0.ckan
  MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.3.1.ckan
Labels: Fix relationships

#2500 Fix install_to capitalization of Scatterer config and sunflare
  Scatterer-config/Scatterer-config-3-v0.0824.ckan
  Scatterer-config/Scatterer-config-3-v0.0825.ckan
  Scatterer-sunflare/Scatterer-sunflare-3-v0.0824.ckan
  Scatterer-sunflare/Scatterer-sunflare-3-v0.0825.ckan
  Scatterer/Scatterer-3-v0.0824.ckan
  Scatterer/Scatterer-3-v0.0825.ckan
Labels: Fix install

#2506 Try to enforce Scatterer compatibility for GPP and GEP
  GPP/GPP-1-1.6.1.1.ckan
  GPP/GPP-1-1.6.1.2.ckan
  GPP/GPP-1-1.6.2.1.ckan
  GPP/GPP-1-1.6.2.2.ckan
  GPP/GPP-1-1.6.3.0.ckan
  GPP/GPP-1-1.6.3.1.ckan
  GPP/GPP-1-1.6.4.0.ckan
  GPP/GPP-1-1.6.4.1.ckan
  GPP/GPP-1-1.6.4.2.ckan
  GPP/GPP-1-1.6.5.0.ckan
  GPP/GPP-1-1.6.6.0.ckan
  GPP/GPP-1-1.6.7.0.ckan
  GPP/GPP-1.5.1.ckan
  GPP/GPP-1.5.2.ckan
  GPP/GPP-1.5.3.ckan
  GPP/GPP-1.5.88.ckan
  GPP/GPP-1.5.99.ckan
  GPP/GPP-1.6.0.1.ckan
  GPP/GPP-1.6.0.ckan
  GPP/GPP-1.6.1.0.ckan
  GPPCloudsHighRes/GPPCloudsHighRes-1.5.2.ckan
  GPPCloudsLowRes/GPPCloudsLowRes-1.5.2.ckan
  GPPSecondary/GPPSecondary-1.5.1.ckan
  GPPSecondary/GPPSecondary-1.5.2.ckan
  GPPSecondary/GPPSecondary-1.5.3.ckan
  GPPSecondary/GPPSecondary-1.5.88.ckan
  GPPSecondary/GPPSecondary-1.5.99.ckan
  GPPSecondary/GPPSecondary-1.6.0.1.ckan
  GPPSecondary/GPPSecondary-1.6.0.ckan
  GPPSecondary/GPPSecondary-1.6.1.1.ckan
  GPPSecondary/GPPSecondary-1.6.1.2.ckan
  GPPSecondary/GPPSecondary-1.6.2.0.ckan
  GPPSecondary/GPPSecondary-1.6.2.1.ckan
  GPPSecondary/GPPSecondary-1.6.2.2.ckan
  GPPSecondary/GPPSecondary-1.6.3.0.ckan
  GPPSecondary/GPPSecondary-1.6.3.1.ckan
  GPPSecondary/GPPSecondary-1.6.4.0.ckan
  GPPSecondary/GPPSecondary-1.6.4.1.ckan
  GPPSecondary/GPPSecondary-1.6.4.2.ckan
  GPPSecondary/GPPSecondary-1.6.5.0.ckan
  GPPSecondary/GPPSecondary-1.6.6.0.ckan
  GPPSecondary/GPPSecondary-1.6.7.0.ckan
  GrannusExpansionPack/GrannusExpansionPack-1.1.1.ckan
  GrannusExpansionPack/GrannusExpansionPack-1.1.2.ckan
  GrannusExpansionPack/GrannusExpansionPack-1.1.3.ckan
  GrannusExpansionPack/GrannusExpansionPack-1.1.4.ckan
  GrannusExpansionPack/GrannusExpansionPack-1.1.5.ckan
  GrannusExpansionPack/GrannusExpansionPack-1.1.6.ckan
  GrannusExpansionPack/GrannusExpansionPack-1.2.0.ckan
  GrannusExpansionPack/GrannusExpansionPack-1.2.1.ckan
  GrannusExpansionPack/GrannusExpansionPack-1.2.2.ckan
  GrannusExpansionPack/GrannusExpansionPack-1.2.3.ckan
  GrannusExpansionPack/GrannusExpansionPack-1.2.4.ckan
  GrannusExpansionPack/GrannusExpansionPack-1.2.5.ckan
Labels: Fix relationships

#2513 Add conflicts between ContractConfigurator-HistoricMissions variants
  ContractConfigurator-HistoricMissions/ContractConfigurator-HistoricMissions-1.7.1.frozen
  ContractConfigurator-HistoricMissions/ContractConfigurator-HistoricMissions-1.9.0.ckan
  ContractConfigurator-HistoricMissions/ContractConfigurator-HistoricMissions-2.0.0.ckan
  ContractConfigurator-HistoricMissions/ContractConfigurator-HistoricMissions-2.0.1.ckan
  ContractConfigurator-HistoricMissions/ContractConfigurator-HistoricMissions-2.1.0.ckan
  ContractConfigurator-HistoricMissions/ContractConfigurator-HistoricMissions-2.2.0.ckan
  ContractConfigurator-HistoricMissions/ContractConfigurator-HistoricMissions-2.3.0.ckan
  ContractConfigurator-HistoricMissionsRSS/ContractConfigurator-HistoricMissionsRSS-1.9.0.ckan
  ContractConfigurator-HistoricMissionsRSS/ContractConfigurator-HistoricMissionsRSS-2.0.0.ckan
  ContractConfigurator-HistoricMissionsRSS/ContractConfigurator-HistoricMissionsRSS-2.0.1.ckan
  ContractConfigurator-HistoricMissionsRSS/ContractConfigurator-HistoricMissionsRSS-2.1.0.ckan
  ContractConfigurator-HistoricMissionsRSS/ContractConfigurator-HistoricMissionsRSS-2.2.0.ckan
  ContractConfigurator-HistoricMissionsRSS/ContractConfigurator-HistoricMissionsRSS-2.3.0.ckan
Labels: Easy, Fix relationships
