Repository KSP-CKAN/CKAN-meta, pull requests merged in 2021-03, with the labels that each got.

#2296 Fix compatibility of frozen mods
  GPO/GPO-3.3.1.ckan
  GPO/GPO-3.4.0.ckan
  SemioticStandard/SemioticStandard-1.1.1.ckan
Labels: Easy, Fix compatibility

#2297 Set BluedogDB v1.7.0 min KSP version to 1.8.1
  BluedogDB/BluedogDB-v1.7.0.ckan
Labels: Easy, Fix compatibility

#2298 Make Kerbalism-Config-RO conflict with life support mods
  Kerbalism-Config-RO/Kerbalism-Config-RO-v0.1.1.ckan
  Kerbalism-Config-RO/Kerbalism-Config-RO-v0.1.2.ckan
  Kerbalism-Config-RO/Kerbalism-Config-RO-v0.1.ckan
  Kerbalism-Config-RO/Kerbalism-Config-RO-v0.2.ckan
  Kerbalism-Config-RO/Kerbalism-Config-RO-v0.9.1.ckan
  Kerbalism-Config-RO/Kerbalism-Config-RO-v0.9.ckan
Labels: Easy, Fix relationships

#2310 Delete removed release of PartlyColoredSuits
  PartlyColoredSuits/PartlyColoredSuits-1.0.3_Inconsistent_Naming_Particularly_Obvious.ckan
Labels: Easy, Fix versioning

#2311 Make recent DLCs compatible with KSP 1.11.2
  BreakingGround-DLC/BreakingGround-DLC-1.6.0.ckan
  BreakingGround-DLC/BreakingGround-DLC-1.6.1.ckan
  MakingHistory-DLC/MakingHistory-DLC-1.11.0.ckan
  MakingHistory-DLC/MakingHistory-DLC-1.11.1.ckan
Labels: Easy, Fix compatibility

#2312 Freeze KSPW00tNow
  KSPW00tNow/KSPW00tNow-0.2.1.frozen
Labels: Fix relationships

#2317 Mark Harmony1 bundlers
  AirlockPlus/AirlockPlus-v0.0.10.ckan
  AirlockPlus/AirlockPlus-v0.0.9.ckan
  Kerbalism/Kerbalism-3.0.1.ckan
  Kerbalism/Kerbalism-3.0.2.ckan
  Kerbalism/Kerbalism-3.0.ckan
  Kerbalism/Kerbalism-3.1.ckan
  Kerbalism/Kerbalism-3.10.ckan
  Kerbalism/Kerbalism-3.11.ckan
  Kerbalism/Kerbalism-3.2.ckan
  Kerbalism/Kerbalism-3.3.ckan
  Kerbalism/Kerbalism-3.4.ckan
  Kerbalism/Kerbalism-3.5.ckan
  Kerbalism/Kerbalism-3.6.ckan
  Kerbalism/Kerbalism-3.7.ckan
  Kerbalism/Kerbalism-3.8.ckan
  Kerbalism/Kerbalism-3.9.ckan
  LunaMultiplayer/LunaMultiplayer-0.26.0.ckan
  TiltEm/TiltEm-1.2.0.ckan
  TiltEm/TiltEm-1.2.1.ckan
  TiltEm/TiltEm-1.2.2.ckan
Labels: Fix relationships

#2325 Revert BluedogDB-v1.7.1 compat change
  BluedogDB/BluedogDB-v1.7.1.ckan
Labels: Easy, Fix compatibility

#2327 Make StandardPropulsionSystems indefinitely compatible
  StandardPropulsionSystems/StandardPropulsionSystems-1.0.5.ckan
Labels: Easy, Fix compatibility
