Repository KSP-CKAN/CKAN-meta, pull requests merged in 2021-06, with the labels that each got.

#2343 Freeze all HumanStuff releases as requested by author
  HumanStuff/HumanStuff-1-v1.0.4.1.frozen
  HumanStuff/HumanStuff-1-v1.0.4.frozen
  HumanStuff/HumanStuff-1-v1.0.5.2.frozen
  HumanStuff/HumanStuff-1-v1.0.5.3.frozen
  HumanStuff/HumanStuff-1-v1.0.5.4.frozen
  HumanStuff/HumanStuff-1-v1.1.0.0.frozen
  HumanStuff/HumanStuff-1-v1.1.0.1.frozen
  HumanStuff/HumanStuff-1-v1.1.1.frozen
  HumanStuff/HumanStuff-1-v1.2.1.frozen
  HumanStuff/HumanStuff-1-v1.3.1.frozen
  HumanStuff/HumanStuff-v1.0.3.frozen
  HumanStuff/HumanStuff-v1.0.4_Freedom_Vostok_One_-_Lift_Off_for_KSP_1.8.1_v1.10.1_CKAN.frozen
Labels: Freeze

#2344 Freeze BuranEnergia
  BuranEnergia/BuranEnergia-1.0.frozen
  BuranEnergia/BuranEnergia-1.1.frozen
Labels: Easy, Fix license

#2345 Fix ROEngines historical licenses
  ROEngines/ROEngines-v1.3.1.0.ckan
  ROEngines/ROEngines-v1.4.0.0.ckan
  ROEngines/ROEngines-v1.5.ckan
  ROEngines/ROEngines-v1.6.ckan
Labels: Easy, Fix license

#2346 Update TheWorldBeyond license and compatibility
  TheWorldBeyond/TheWorldBeyond-v1.1.1.ckan
Labels: Easy, Fix compatibility, Fix license

#2375 Add InterstellarRedistributable dependency to KSPIE
  KSPInterstellarExtended/KSPInterstellarExtended-1.28.12.ckan
Labels: Fix relationships
