Repository KSP-CKAN/CKAN-meta, pull requests merged in 2021-07, with the labels that each got.

#2376 Freeze TerrasIgnotas and SystemicBodyCollection
  SystemicBodyCollection/SystemicBodyCollection-0.4.frozen
  TerrasIgnotas/TerrasIgnotas-0.1.1.frozen
  TerrasIgnotas/TerrasIgnotas-0.1.2.frozen
  TerrasIgnotas/TerrasIgnotas-0.1.3.frozen
  TerrasIgnotas/TerrasIgnotas-0.1.4.frozen
Labels: Freeze

#2379 Fix RP-0 compat
  RP-0/RP-0-v1.10.0.1.ckan
Labels: Easy, Fix compatibility

#2382 Update compatibility of Parallax 1.2.3
  Parallax/Parallax-1.2.3.ckan
Labels: Fix compatibility

#2384 Fix EditorExtensionsRedux compat
  EditorExtensionsRedux/EditorExtensionsRedux-3.4.3.ckan
Labels: Easy, Fix compatibility

#2385 Freeze AstronomersPack modules
  AstronomersPack-AtmosphericScattering/AstronomersPack-AtmosphericScattering-Interstellar.V2.frozen
  AstronomersPack-Auroras-4K/AstronomersPack-Auroras-4K-Interstellar.V2.frozen
  AstronomersPack-Auroras-8K/AstronomersPack-Auroras-8K-Interstellar.V2.frozen
  AstronomersPack-Clouds-High/AstronomersPack-Clouds-High-Interstellar.V2.frozen
  AstronomersPack-Clouds-Low/AstronomersPack-Clouds-Low-Interstellar.V2.frozen
  AstronomersPack-Clouds-Medium/AstronomersPack-Clouds-Medium-Interstellar.V2.frozen
  AstronomersPack-DistantObjectEnhancement/AstronomersPack-DistantObjectEnhancement-Interstellar.V2.frozen
  AstronomersPack-Eve-Jool-Clouds-2K/AstronomersPack-Eve-Jool-Clouds-2K-Interstellar.V2.frozen
  AstronomersPack-Eve-Jool-Clouds-4K/AstronomersPack-Eve-Jool-Clouds-4K-Interstellar.V2.frozen
  AstronomersPack-Eve-Jool-Clouds-8K/AstronomersPack-Eve-Jool-Clouds-8K-Interstellar.V2.frozen
  AstronomersPack-Lightning/AstronomersPack-Lightning-Interstellar.V2.frozen
  AstronomersPack-PlanetShine/AstronomersPack-PlanetShine-Interstellar.V2.frozen
  AstronomersPack-Sandstorms/AstronomersPack-Sandstorms-Interstellar.V2.frozen
  AstronomersPack-Snow/AstronomersPack-Snow-Interstellar.V2.frozen
  AstronomersPack-SurfaceGlow/AstronomersPack-SurfaceGlow-Interstellar.V2.frozen
  AstronomersPack/AstronomersPack-Interstellar.V2.frozen
Labels: Freeze

#2389 Fix GPP mod suite compat and dependencies
  GPP/GPP-1-1.6.4.0.ckan
  GPP/GPP-1-1.6.4.1.ckan
  GPP/GPP-1-1.6.4.2.ckan
  GPPCloudsHighRes/GPPCloudsHighRes-1.6.4.0.ckan
  GPPCloudsHighRes/GPPCloudsHighRes-1.6.4.1.ckan
  GPPCloudsHighRes/GPPCloudsHighRes-1.6.4.2.ckan
  GPPCloudsLowRes/GPPCloudsLowRes-1.6.4.0.ckan
  GPPCloudsLowRes/GPPCloudsLowRes-1.6.4.1.ckan
  GPPCloudsLowRes/GPPCloudsLowRes-1.6.4.2.ckan
  GPPSecondary/GPPSecondary-1.6.4.0.ckan
  GPPSecondary/GPPSecondary-1.6.4.1.ckan
  GPPSecondary/GPPSecondary-1.6.4.2.ckan
  GPPTextures/GPPTextures-3.0.0.ckan
  GPPTextures/GPPTextures-4.0.0.ckan
  GPPTextures/GPPTextures-4.1.0.ckan
  GPPTextures/GPPTextures-4.1.1.ckan
  GPPTextures/GPPTextures-4.2.0.ckan
Labels: Fix compatibility, Fix install, Fix relationships

#2392 Purge rogue tag
  Notes2Log/Notes2Log-0.0.1.ckan
  Notes2Log/Notes2Log-0.0.2.ckan
Labels: Easy

#2395 Fix xScienceContinued dependencies
  xScienceContinued/xScienceContinued-6.0.0.7.ckan
Labels: Fix relationships
