Repository KSP-CKAN/CKAN-meta, pull requests merged in 2021-01, with the labels that each got.

#2230 Add KerbinSideRemastered to KSCExtended's depdenencies
  KSCExtended/KSCExtended-2.0.ckan
  KSCExtended/KSCExtended-2.1.ckan
Labels: Easy, Fix relationships

#2231 Fix PlanesWithPurposes install stanza
  ContractConfigurator-PlanesWithPurposes/ContractConfigurator-PlanesWithPurposes-1.2.ckan
  ContractConfigurator-PlanesWithPurposes/ContractConfigurator-PlanesWithPurposes-1.3.ckan
Labels: Fix install

#2234 Move KIS back to Extraplanetary Launchpads's historical recommends list
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-5.1.90.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-5.1.92.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-5.1.93.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-5.1.94.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-5.5.3.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-5.6.0.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-5.7.1.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-5.7.2.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-5.8.0.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-5.9.0.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.0.0.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.1.0.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.2.0.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.2.1.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.2.2.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.3.0.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.3.1.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.3.2.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.3.3.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.3.4.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.3.5.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.4.0.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.5.0.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.5.1.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.6.0.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.6.1.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.6.2.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.7.0.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.7.1.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.7.2.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.7.3.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.8.0.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.8.1.0.ckan
  ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-6.8.2.0.ckan
Labels: Easy, Fix relationships

#2235 Update KIS-1.27.ckan
  KIS/KIS-1.27.ckan
Labels: Fix compatibility

#2238 Update MissingHistory-1.8.2.ckan
  MissingHistory/MissingHistory-1.3.2.ckan
  MissingHistory/MissingHistory-1.3.3.ckan
  MissingHistory/MissingHistory-1.3.ckan
  MissingHistory/MissingHistory-1.4.ckan
  MissingHistory/MissingHistory-1.7.2.ckan
  MissingHistory/MissingHistory-1.7.3.ckan
  MissingHistory/MissingHistory-1.8.1.ckan
  MissingHistory/MissingHistory-1.8.2.ckan
  MissingHistory/MissingHistory-1.8.ckan
Labels: Fix compatibility

#2240 Freeze kOS 1.3.0.0
  kOS/kOS-1-1.3.0.0.frozen
Labels: Fix versioning

#2244 Freeze WasdEditorCameraContinued after 0.7.0.1
  WasdEditorCameraContinued/WasdEditorCameraContinued-0.7.1.1.frozen
  WasdEditorCameraContinued/WasdEditorCameraContinued-0.7.1.2.frozen
  WasdEditorCameraContinued/WasdEditorCameraContinued-0.7.1.frozen
Labels: Easy

#2245 Cache permissions workaround
  .github/workflows/validate.yml
Labels: Easy

#2246 Fix MissingHistory 1.9 compat and install
  MissingHistory/MissingHistory-1.9.ckan
Labels: Easy, Fix compatibility, Fix install

#2247 Update MissingHistory 1.9 compat again
  MissingHistory/MissingHistory-1.9.ckan
Labels: Fix compatibility
