Repository KSP-CKAN/CKAN-meta, pull requests merged in 2022-09, with the labels that each got.

#3094 Freeze mods downloading from deleted GitHub repositories
  CargoTransportationSolutions/CargoTransportationSolutions-0.4.2.frozen
  CargoTransportationSolutions/CargoTransportationSolutions-0.5.0.frozen
  CargoTransportationSolutions/CargoTransportationSolutions-0.5.1.frozen
  CargoTransportationSolutions/CargoTransportationSolutions-0.5.3.frozen
  ConstellationEssentials/ConstellationEssentials-v1.4.1.0.frozen
  CrowdSourcedFlags/CrowdSourcedFlags-1.15.1.frozen
  CrowdSourcedFlags/CrowdSourcedFlags-1.42.3.frozen
  CrowdSourcedFlags/CrowdSourcedFlags-1.49.4.frozen
  CrowdSourcedFlags/CrowdSourcedFlags-1.50.5.frozen
  CrowdSourcedFlags/CrowdSourcedFlags-1.55.5.frozen
  FreedomTex/FreedomTex-1-v1.5.1.0.frozen
  FreedomTex/FreedomTex-1-v1.5.frozen
  FusTek-SharedAssets/FusTek-SharedAssets-1.0.frozen
  KerbQuakeExtended/KerbQuakeExtended-1.2.2.2.frozen
  RealisticHeatMgmt/RealisticHeatMgmt-1.1.frozen
  SSRSS-Clouds-HR/SSRSS-Clouds-HR-v0.0.2.5.frozen
  SSRSS-Clouds-HR/SSRSS-Clouds-HR-v0.0.2.6.frozen
  SSRSS-Clouds-HR/SSRSS-Clouds-HR-v0.0.2.7.frozen
  SSRSS-Clouds-HR/SSRSS-Clouds-HR-v0.0.2.8.frozen
  SSRSS-Clouds-HR/SSRSS-Clouds-HR-v0.0.2.9.frozen
  SSRSS-Clouds-HR/SSRSS-Clouds-HR-v0.0.3.0.frozen
  SSRSS-Clouds-HR/SSRSS-Clouds-HR-v0.0.3.1.frozen
  SSRSS-Clouds-HR/SSRSS-Clouds-HR-v0.0.3.2.frozen
  SSRSS-Clouds-LR/SSRSS-Clouds-LR-v0.0.2.5.frozen
  SSRSS-Clouds-LR/SSRSS-Clouds-LR-v0.0.2.6.frozen
  SSRSS-Clouds-LR/SSRSS-Clouds-LR-v0.0.2.7.frozen
  SSRSS-Clouds-LR/SSRSS-Clouds-LR-v0.0.2.8.frozen
  SSRSS-Clouds-LR/SSRSS-Clouds-LR-v0.0.2.9.frozen
  SSRSS-Clouds-LR/SSRSS-Clouds-LR-v0.0.3.0.frozen
  SSRSS-Clouds-LR/SSRSS-Clouds-LR-v0.0.3.1.frozen
  SSRSS-Clouds-LR/SSRSS-Clouds-LR-v0.0.3.2.frozen
  SSRSS-Cont/SSRSS-Cont-v0.0.2.1.frozen
  SSRSS-Cont/SSRSS-Cont-v0.0.2.2.frozen
  SSRSS-Cont/SSRSS-Cont-v0.0.2.5.frozen
  SSRSS-Cont/SSRSS-Cont-v0.0.2.6.frozen
  SSRSS-Cont/SSRSS-Cont-v0.0.2.7.frozen
  SSRSS-Cont/SSRSS-Cont-v0.0.2.8.frozen
  SSRSS-Cont/SSRSS-Cont-v0.0.2.9.frozen
  SSRSS-Cont/SSRSS-Cont-v0.0.3.0.frozen
  SSRSS-Cont/SSRSS-Cont-v0.0.3.1.frozen
  SSRSS-Cont/SSRSS-Cont-v0.0.3.2.frozen
  SSRSS-StockIncl/SSRSS-StockIncl-v0.0.2.5.frozen
  SSRSS-StockIncl/SSRSS-StockIncl-v0.0.2.6.frozen
  SSRSS-StockIncl/SSRSS-StockIncl-v0.0.2.7.frozen
  SSRSS-StockIncl/SSRSS-StockIncl-v0.0.2.8.frozen
  SSRSS-StockIncl/SSRSS-StockIncl-v0.0.2.9.frozen
  SSRSS-StockIncl/SSRSS-StockIncl-v0.0.3.0.frozen
  SSRSS-StockIncl/SSRSS-StockIncl-v0.0.3.1.frozen
  SSRSS-StockIncl/SSRSS-StockIncl-v0.0.3.2.frozen
  SVE-HighResolution/SVE-HighResolution-1.0.0R.frozen
  SVE-LowResolution/SVE-LowResolution-1.0.0R.frozen
  SVE-MediumResolution/SVE-MediumResolution-1.0.0R.frozen
  SVE-UltraResolution/SVE-UltraResolution-1.0.0R.frozen
  ScottManleyHeadPack/ScottManleyHeadPack-v1.0.frozen
  Skillz/Skillz-1.0.4.frozen
Labels: Easy, Freeze

#3095 Fix SpaceDock deep links
  DynamicBatteryStorage/DynamicBatteryStorage-1.0.0.ckan
  KSPRC-Textures/KSPRC-Textures-0.7.ckan
  SASS-RevJ/SASS-RevJ-1.ckan
  SASS-SE/SASS-SE-1.0.ckan
Labels: Easy

#3096 Trim extra characters from resources.repository
  CommunityRealAgencyPack/CommunityRealAgencyPack-v1.0.ckan
  DSDMobileProcessingLabs/DSDMobileProcessingLabs-1.0.0.ckan
  DSDMobileProcessingLabs/DSDMobileProcessingLabs-1.0.ckan
  ExplodiumBreathingEngines/ExplodiumBreathingEngines-1.0.0.ckan
  ExplodiumBreathingEngines/ExplodiumBreathingEngines-1.1.0.ckan
  InlineBallutes/InlineBallutes-1.2.1.ckan
  InlineBallutes/InlineBallutes-1.2.2.ckan
  InlineBallutes/InlineBallutes-1.2.3.ckan
  JackOLantern/JackOLantern-1.0.0.1.ckan
  JackOLantern/JackOLantern-1.0.0.2.ckan
  LIME/LIME-v1.0.1.ckan
  LIME/LIME-v1.1.0.ckan
  LIME/LIME-v1.1.1.ckan
  LIME/LIME-v1.1.2.ckan
  MicroSatRevived/MicroSatRevived-0.1.0.ckan
  MicroSatRevived/MicroSatRevived-0.1.1.ckan
  MicroSatRevived/MicroSatRevived-0.1.2.1.ckan
  MicroSatRevived/MicroSatRevived-0.1.2.2.ckan
  MicroSatRevived/MicroSatRevived-0.1.2.3.ckan
  MicroSatRevived/MicroSatRevived-0.1.2.4.ckan
  MicroSatRevived/MicroSatRevived-0.1.2.5.ckan
  MicroSatRevived/MicroSatRevived-0.1.2.6.ckan
  MicroSatRevived/MicroSatRevived-0.1.2.7.ckan
  MicroSatRevived/MicroSatRevived-0.1.2.8.ckan
  MicroSatRevived/MicroSatRevived-0.1.2.ckan
  MicroSatRevived/MicroSatRevived-0.1.3.1.ckan
  MicroSatRevived/MicroSatRevived-0.1.3.2.ckan
  MicroSatRevived/MicroSatRevived-0.1.3.ckan
  ORANGE/ORANGE-v1.0.0.ckan
  ORANGE/ORANGE-v1.0.2.ckan
  ORANGE/ORANGE-v1.0.3.ckan
  PEAR/PEAR-v1.0.0.ckan
  PEAR/PEAR-v1.0.1.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.0.1.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.1.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.10.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.11.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.12.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.13.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.14.1.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.14.2.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.14.3.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.14.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.2.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.3.1.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.3.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.4.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.5.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.6.1.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.6.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.7.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.8.ckan
  QuizTechAeroPackContinued/QuizTechAeroPackContinued-1.3.9.ckan
  RealAgenciesCollection/RealAgenciesCollection-v1.0.4.ckan
Labels: Easy

#3097 Move "FLEET" mods into identifier folders
  EPL-ISRU/EPL-ISRU-1.0.ckan
  EPL-MKS/EPL-MKS-1.0.ckan
  EPL-fastbuild/EPL-fastbuild-1.0.ckan
Labels: Easy

#3098 Fix blackheart texture downloads
  ProceduralParts-Textures-SCCKSCS/ProceduralParts-Textures-SCCKSCS-0.ckan
  ProceduralParts-Textures-SCCKSCS/ProceduralParts-Textures-SCCKSCS-1.ckan
Labels: Easy

#3099 Fix blackheart textures homepage
  ProceduralParts-Textures-SCCKSCS/ProceduralParts-Textures-SCCKSCS-0.ckan
  ProceduralParts-Textures-SCCKSCS/ProceduralParts-Textures-SCCKSCS-1.ckan
Labels: Easy

#3100 Fix WBI USI play mode download
  WildBlue-PlayMode-USI/WildBlue-PlayMode-USI-v1.0.0.2.ckan
Labels: Easy

#3101 Couple Parallax-StockTextures releases with the corresponding Parallax release
  Parallax-StockTextures/Parallax-StockTextures-1.1.0_-_PRE.ckan
  Parallax-StockTextures/Parallax-StockTextures-1.1.1.ckan
  Parallax-StockTextures/Parallax-StockTextures-1.1.1b.ckan
  Parallax-StockTextures/Parallax-StockTextures-1.2.1.ckan
  Parallax-StockTextures/Parallax-StockTextures-1.2.2.ckan
  Parallax-StockTextures/Parallax-StockTextures-1.2.3.ckan
  Parallax-StockTextures/Parallax-StockTextures-1.3.0.ckan
  Parallax-StockTextures/Parallax-StockTextures-1.3.1.ckan
Labels: Fix relationships

#3102 Freeze broken ProceduralParts release
  ProceduralParts/ProceduralParts-v2.4.2.frozen
Labels: Easy, Freeze

#3108 Freeze KcalbelohSystem
  KcalbelohSystem/KcalbelohSystem-v1.0.0.frozen
Labels: Freeze

#3109 Freeze MK3PodIVAReplacementbyApex (dup of Mk3InternalsApex)
  MK3PodIVAReplacementbyApex/MK3PodIVAReplacementbyApex-0.1.1.frozen
Labels: Easy, Freeze

#3110 Add FruitGoose as author to FruitGoose's mods
  APPLE/APPLE-1-1.1.9.ckan
  FIG/FIG-1-1.0.2.ckan
  GRAPES/GRAPES-1-1.0.2.ckan
  LIME/LIME-1-1.1.3.ckan
  MANGO/MANGO-1-1.1.1.ckan
  ORANGE/ORANGE-1-1.0.3.1.ckan
  PEAR/PEAR-1-1.0.2.ckan
  PRUNES/PRUNES-1-1.0.1.ckan
  VertikalSpeedIndicator/VertikalSpeedIndicator-1-1.2.1.1.ckan
  VertikalSpeedIndicator/VertikalSpeedIndicator-1-1.2.1.2.ckan
  VertikalSpeedIndicator/VertikalSpeedIndicator-1-1.2.1.ckan
Labels: Easy
