Repository KSP-CKAN/CKAN-meta, pull requests merged in 2022-08, with the labels that each got.

#2903 Spectra ckan fixes
  Spectra/Spectra-v1.1.3.ckan
  Spectra/Spectra-v1.1.4.ckan
  Spectra/Spectra-v1.1.5.ckan
  Spectra/Spectra-v1.1.6.ckan
  Spectra/Spectra-v1.1.7.ckan
  Spectra/Spectra-v1.2.1.ckan
  Spectra/Spectra-v1.2.2.ckan
  Spectra/Spectra-v1.2.3.ckan
  Spectra/Spectra-v1.2.4.ckan
  Spectra/Spectra-v1.2.5.ckan
Labels: Fix relationships

#3041 Freeze old HooliganLabsAirships versions
  HooliganLabsAirships/HooliganLabsAirships-3.0.0.frozen
  HooliganLabsAirships/HooliganLabsAirships-5.2.1.frozen
  HooliganLabsAirships/HooliganLabsAirships-5.3.frozen
  HooliganLabsAirships/HooliganLabsAirships-5.4.frozen
  HooliganLabsAirships/HooliganLabsAirships-6.0.frozen
  HooliganLabsAirships/HooliganLabsAirships-6.1.frozen
  HooliganLabsAirships/HooliganLabsAirships-6.2.frozen
  HooliganLabsAirships/HooliganLabsAirships-6.3.1.frozen
  HooliganLabsAirships/HooliganLabsAirships-6.3.frozen
  HooliganLabsAirships/HooliganLabsAirships-6.4.frozen
Labels: Freeze

#3083 Freeze RealRoster and update its homepage
  RealRoster/RealRoster-v2.1.frozen
Labels: Freeze

#3084 Add conflicts to KHNS for provides
  KerbolsHumbleNeighboringStars/KerbolsHumbleNeighboringStars-1-Beta-1.1.ckan
  KerbolsHumbleNeighboringStars/KerbolsHumbleNeighboringStars-1-Beta-1.2.ckan
Labels: Fix relationships

#3087 Freeze Moldavite 1.3a
  MoldaviteMachines/MoldaviteMachines-1.3a.frozen
  MoldaviteMachinesKerbalism/MoldaviteMachinesKerbalism-1.3a.frozen
Labels: Easy, Freeze

#3092 Switch FoxDefenseContracts to BDArmoryForRunwayProject
  FoxDefenseContracts/FoxDefenseContracts-1.2.ckan
  FoxDefenseContracts/FoxDefenseContracts-1.3.ckan
  FoxDefenseContracts/FoxDefenseContracts-1.4.ckan
  FoxDefenseContracts/FoxDefenseContracts-2.0.ckan
Labels: Easy, Fix relationships

#3093 Epoch historical KerbalWind versions
  KerbalWind/KerbalWind-1-7.1.ckan
  KerbalWind/KerbalWind-1-R10.ckan
  KerbalWind/KerbalWind-1-R11.ckan
  KerbalWind/KerbalWind-1-R12.ckan
  KerbalWind/KerbalWind-1-R13.ckan
  KerbalWind/KerbalWind-1-R8.ckan
  KerbalWind/KerbalWind-1-R9.ckan
Labels: Fix versioning
